servers:
  - host: server1.example.com
    user: username
    remotePath: folder/example12.tar.gz
    folders:
      - /path/to/folder1
      - /path/to/folder2
  - host: server2.example.com
    user: username
    remotePath: folder/example3.tar.gz
    folders:
      - /path/to/folder3
